Edit workflow file

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -2,6 +2,12 @@ name: Build OpenWrt
 
 on:
   workflow_dispatch:
+    inputs:
+        openwrt_version:
+            description: "OpenWrt version tag"
+            required: false
+            type: string
+            default: ""
 
 permissions:
   contents: write
@@ -14,17 +20,34 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v4
 
-      - name: Get latest OpenWrt release
+        - name: Select OpenWrt release
         id: version
+        env:
+        REQUESTED_VERSION: ${{ inputs.openwrt_version }}
         run: |
-          VERSION=$(git ls-remote --tags https://github.com/openwrt/openwrt.git \
-            | grep -oE 'refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$' \
-            | sed 's#refs/tags/##' \
-            | sort -V \
-            | tail -n1)
+            if [ -n "$REQUESTED_VERSION" ]; then
+                VERSION="$REQUESTED_VERSION"
+            else
+                VERSION="$(
+                git ls-remote --tags https://github.com/openwrt/openwrt.git \
+                    | awk -F/ '/refs\/tags\/v[0-9]+\.[0-9]+\.[0-9]+$/ { print $3 }' \
+                    | sort -V \
+                    | tail -n1
+                )"
+            fi
 
-          echo "version=$VERSION" >> $GITHUB_OUTPUT
-          echo "Latest OpenWrt: $VERSION"
+            if ! git ls-remote --exit-code --tags \
+                https://github.com/openwrt/openwrt.git \
+                "refs/tags/$VERSION" >/dev/null; then
+                echo "Tag not found: $VERSION"
+                exit 1
+            fi
+
+            RELEASE_VERSION="${VERSION#v}"
+
+            echo "version=$VERSION" >> "$GITHUB_OUTPUT"
+            echo "release_version=$RELEASE_VERSION" >> "$GITHUB_OUTPUT"
+            echo "Building OpenWrt: $VERSION"
     
       - name: Install dependencies
         run: |
@@ -76,6 +99,7 @@ jobs:
               -name "*.img.gz" -o \
               -name "*.itb" -o \
               -name "*.tar" \
+              -name "*.tar.zst" \
             \) \
             -exec cp {} release/ \;
 
